Lex/fee fetch loop
EdgeApp/edge-fee-tracker pull request #3
Opened 2021-06-14 18:47 UTC by LPeterson18

1. Updated Databases to structure around partners
2. Added fetch calls for ethgasstation.info, mempool.space, and bitcoinfees.earn.com
3. Added engine to fetch from APIs and add collected fees to DBs with normalized dates as Ids

2021-06-15 17:45 UTC, LPeterson18 commented
Rename and restructure files and folders for better readability

2021-06-16 00:28 UTC, LPeterson18 commented
Re-organized file structure as detailed during PR review

2021-06-17 02:31 UTC, thehobbit85 requested changes
See comment

2021-06-17 02:31 UTC, thehobbit85 commented on src/feesEngine.ts
> +      if (feesResult[0] != null) {
This should probably be `feesResult[1]` no?

2021-06-17 15:46 UTC, LPeterson18 commented
Fixed error handling

2021-06-17 16:00 UTC, LPeterson18 commented
Rebased branch

2021-06-21 17:47 UTC, LPeterson18 commented on src/partners/earn.ts
> +  const url = `https://bitcoinfees.earn.com/api/v1/fees/list`
Base URIs for all providers should be in config file

2021-06-21 17:55 UTC, LPeterson18 commented on src/feesEngine.ts
> +    const ethGasStation = ethGasStationCall()
Handle result/rejected promises on each one and not on returned array from promise.all

2021-06-21 17:56 UTC, LPeterson18 commented on src/feesEngine.ts
> +  await new Promise((resolve: Function) => setTimeout(resolve, ms))
Move to utils file

2021-06-21 23:20 UTC, LPeterson18 commented
1. Moved Base URIs to config
2. Changed engine to handle resolved/rejected promises on each one and not on returned array from promise.all
3. Moved snooze to utils
4. Reorganized commits

2021-06-22 17:41 UTC, LPeterson18 commented
1. Reduced fees processing logic into one function using cleaners

2021-06-23 00:47 UTC, LPeterson18 commented
Removed redundant code by creating generic fetch function

2021-06-23 02:01 UTC, LPeterson18 commented
Fixed eslint-disable-next-line and rebased branch

2021-06-23 02:03 UTC, thehobbit85 approved these changes

2021-06-23 02:03 UTC, merged