Lex/sidebar
EdgeApp/edge-fee-tracker pull request #5
Opened 2021-06-15 01:57 UTC by LPeterson18

1. Added App.tsx file
2. Added sidebar component

2021-06-15 18:32 UTC, thehobbit85 requested changes
See comments

2021-06-15 18:32 UTC, thehobbit85 commented on src/client/App.tsx
> +}
This doesn't seem to be used anywhere.

2021-06-15 18:32 UTC, thehobbit85 commented on src/client/components/Sidebar.tsx
> +}
Is that used anywhere?

2021-06-16 00:37 UTC, LPeterson18 commented
Removed unnecessary styling

2021-06-16 19:46 UTC, thehobbit85 approved these changes

2021-06-23 04:07 UTC, thehobbit85 approved these changes

2021-06-23 04:07 UTC, merged